version: '3.4'
services:
  
  pdsprofile:
    build:
      context: .
    restart: always
    environment:
      PDS_HOST: pdsprofile-test-pds-server
      PDS_PORT: 8080
    ports:
      - $API_PORT:8080

    
