openapi: 3.0.0
info:
  description: 
    This is a pds-phenotype-mapping-plugin.  You can find
    out more about Swagger at
    [http://swagger.io](http://swagger.io) or on
    [irc.freenode.net, #swagger](http://swagger.io/irc/).
  version: "1.0.0"
  title: pds-profile-plugin
  license:
    name: MIT
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /profile:
    post:
      summary: Generate patient profile
      operationId: api.profile
      parameters:
        - in: query
          name: patient_id
          schema:
            type: string
          required: true
        - in: query
          name: model_plugin_id
          schema:
            type: string
          required: true
        - in: query
          name: timestamp
          schema:
            type: string
            format: date-time
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema: {}
#              $ref: '#/components/schemas/Config'
      responses: # has to match output of dispatcher.py
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
        '405':
          description: Invalid input
components:
  schemas:
    Profile:
      type: array
      items:
        type: object
        properties:
          clinical_feature_variable:
            type: string
            example: "bmi"
          value: {}
          calculation:
            type: string
            example: "record not found"
          certitude:
            type: integer
            example: 0
          description:
            type: string
          title:
            type: string
        required:
          - clinical_feature_variable
          - value
          - calculation
          - certitude
          - description
          - title
    Config:
      type: object
      properties:
        phenotype_mapping_plugin_id:
          type: string
          example: "pds-phenotype-mapping"
        data_provider_plugin_id:
          type: string
          example: "pds-data-provider-mock-fhir"
        custom_units:
          type: array
          items:
            type: object
            properties:
              clinical_feature_variable:
                type: string
                example: "bmi"
              unit:
                type: string
                example: "kg/m^2"
            required:
              - clinical_feature_variable
              - unit
      required:
        - phenotype_mapping_plugin_id
        - data_provider_plugin_id
        

